version: "3"
services:
  mattermost:
    image: localhost/mattermost:latest
    container_name: mattermost-containya
    restart: always

#    ports:
#      - "8065:8065"

    volumes:
      - ./config_docker.json:/mm/mattermost/config/config_docker.json
      - nginx-certific8s:/mm/mattermost/certs:ro
      - mm-mattermost-data:/mm/mattermost-data
      - mm-postgresql-data:/var/lib/postgresql/data

    networks:
      - containya-network

volumes:
  nginx-certific8s:
    external: true
  mm-mattermost-data:
    external: true
  mm-postgresql-data:
    external: true

networks:
  containya-network:
    external: true
