version: "3"
services:
  mattermost:
    image: localhost/mattermost:latest
    container_name: mattermost-containya
    restart: always

#    ports:
#      - "8065:8065"

    volumes:
      - type: bind
        source: ./config_docker.json
        target: /mm/mattermost/config/config_docker.json

      - type: volume
        source: nginx-certific8s
        target: /mm/mattermost/certs:ro

      - type: volume
        source: mm-mattermost-data
        target: /mm/mattermost-data

      - type: volume
        source: mm-postgresql-data
        target: /var/lib/postgresql/data

    networks:
      - containya-network

volumes:
  nginx-certific8s:
    external: true
  mm-mattermost-data:
    external: true
  mm-postgresql-data:
    external: true

networks:
  containya-network:
    external: true
